### ISSUE TITLE
ChatClient

### ISSUE THREAD

**Issue by hlaaji** [Bikram-Shrestha/Java-Socket-Programming-Chat-Application-#1]
Hello ,
I'm student. I want to use your application.
How to install  and Start ChatClient ?
I use NetBeans (Windows7); I create project JavaFX and I create two java files.
I started ChatServer but the application ChatClient not started, the error message "class did not have main method".
I'm waiting for your response.
Best regards.

**Comment by Bikram-Shrestha** [comment]
Hi @hlaaji , You need to have Java SDK installed and need to compile the code and can run it using cli

**Comment by hlaaji** [comment]
Hi Bikram;
Thank you very much, now it works very well.
I also installed your application "GradeProcessing", the compilation is
good without errors, but when I execute the application that return me:
java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
at
com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:873)
Caused by: java.lang.IllegalStateException: Not on FX application thread;
currentThread = main
at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:229)
at
com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
at javafx.stage.Stage.<init>(Stage.java:241)
at javafx.stage.Stage.<init>(Stage.java:227)
at
javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
at javafx.scene.control.Dialog.<init>(Dialog.java:263)
at javafx.scene.control.Alert.<init>(Alert.java:245)
at javafx.scene.control.Alert.<init>(Alert.java:223)
at encdbc.GradeGUI.<init>(GradeGUI.java:78)    corresponds to line:
private Alert alert = new Alert(Alert.AlertType.ERROR);
at encdbc.GradeGUI.main(GradeGUI.java:682)    correspond to line : new
GradeGUI();
... 11 more
Exception running application encdbc.GradeGUI
/home/hassan/.cache/netbeans/8.1/executor-snippets/run.xml:53: Java
returned: 1
BUILD FAILED (total time: 3 seconds)

Can help me to fix this.
Best regards


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#m_-8716979542784056983_DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 16 févr. 2021 à 05:14, Bikram Shrestha <notifications@github.com> a
écrit :

**Comment by Bikram-Shrestha** [comment]
Closing as it is unrelated to this repo.
